version: "3.8"

services:
  ui:
    build:
      context: ui
    environment:
      REACT_APP_BACKEND_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    links:
      - backend

  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
